// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseCommand: typeof import('./src/components/TermCommand/BaseCommand.vue')['default']
    Command: typeof import('./src/components/TermCommand/Command.vue')['default']
    HistoryCommand: typeof import('./src/components/TermCommand/HistoryCommand.vue')['default']
    InputCommand: typeof import('./src/components/TermCommand/InputCommand.vue')['default']
    TBox: typeof import('./src/components/TermContainer.vue')['default']
    TermBody: typeof import('./src/components/TermBody.vue')['default']
    TermCommand: typeof import('./src/components/TermCommand.vue')['default']
    TermContainer: typeof import('./src/components/TermContainer.vue')['default']
    TermHeader: typeof import('./src/components/TermHeader.vue')['default']
  }
}
