// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseCommand: typeof import('./src/components/TermBody/TermCommand/BaseCommand.vue')['default']
    Command: typeof import('./src/components/TermCommand/BaseCommand.vue')['default']
    HistoryCommand: typeof import('./src/components/TermBody/TermCommand/HistoryCommand.vue')['default']
    InputCommand: typeof import('./src/components/TermBody/TermCommand/InputCommand.vue')['default']
    TBox: typeof import('./src/views/TermContainer.vue')['default']
    TermBody: typeof import('./src/components/TermBody/TermBody.vue')['default']
    TermCommand: typeof import('./src/components/TermCommand.vue')['default']
    TermContainer: typeof import('./src/views/TermContainer.vue')['default']
    TermHeader: typeof import('./src/components/TermHeader/TermHeader.vue')['default']
    TermHelp: typeof import('./src/components/TermBody/TermWelcome/TermHelp.vue')['default']
    TermMessage: typeof import('./src/components/TermMessage/TermMessage.vue')['default']
    TermWelcome: typeof import('./src/components/TermBody/TermWelcome/TermWelcome.vue')['default']
  }
}
